/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthPageSignupRouteImport } from './routes/AuthPage/signup'
import { Route as AuthPageSigninRouteImport } from './routes/AuthPage/signin'
import { Route as AuthenticatedHomeDashboardRouteImport } from './routes/_authenticated/home/Dashboard'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthPageSignupRoute = AuthPageSignupRouteImport.update({
  id: '/AuthPage/signup',
  path: '/AuthPage/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPageSigninRoute = AuthPageSigninRouteImport.update({
  id: '/AuthPage/signin',
  path: '/AuthPage/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeDashboardRoute =
  AuthenticatedHomeDashboardRouteImport.update({
    id: '/home/Dashboard',
    path: '/home/Dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/AuthPage/signin': typeof AuthPageSigninRoute
  '/AuthPage/signup': typeof AuthPageSignupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/home/Dashboard': typeof AuthenticatedHomeDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/AuthPage/signin': typeof AuthPageSigninRoute
  '/AuthPage/signup': typeof AuthPageSignupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/home/Dashboard': typeof AuthenticatedHomeDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/home': typeof HomeRoute
  '/AuthPage/signin': typeof AuthPageSigninRoute
  '/AuthPage/signup': typeof AuthPageSignupRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/home/Dashboard': typeof AuthenticatedHomeDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/AuthPage/signin'
    | '/AuthPage/signup'
    | '/profile'
    | '/home/Dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/AuthPage/signin'
    | '/AuthPage/signup'
    | '/profile'
    | '/home/Dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/home'
    | '/AuthPage/signin'
    | '/AuthPage/signup'
    | '/_authenticated/profile'
    | '/_authenticated/home/Dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HomeRoute: typeof HomeRoute
  AuthPageSigninRoute: typeof AuthPageSigninRoute
  AuthPageSignupRoute: typeof AuthPageSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/AuthPage/signup': {
      id: '/AuthPage/signup'
      path: '/AuthPage/signup'
      fullPath: '/AuthPage/signup'
      preLoaderRoute: typeof AuthPageSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AuthPage/signin': {
      id: '/AuthPage/signin'
      path: '/AuthPage/signin'
      fullPath: '/AuthPage/signin'
      preLoaderRoute: typeof AuthPageSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home/Dashboard': {
      id: '/_authenticated/home/Dashboard'
      path: '/home/Dashboard'
      fullPath: '/home/Dashboard'
      preLoaderRoute: typeof AuthenticatedHomeDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedHomeDashboardRoute: typeof AuthenticatedHomeDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedHomeDashboardRoute: AuthenticatedHomeDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HomeRoute: HomeRoute,
  AuthPageSigninRoute: AuthPageSigninRoute,
  AuthPageSignupRoute: AuthPageSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
